input_dirs:
  bacterial_genomes: "data/raw/bacterial_genomes"
  gene_annotations_bacterial: "data/raw/gene_annotations/bacterial_genomes"
  gene_annotations_phage: "data/raw/gene_annotations/phage_genomes"
  phage_genomes: "data/raw/phage_genomes"
  kmer_frequencies: "data/processed/kmer_frequencies"

output_dirs:
  one_hot_encoded: "data/processed/one_hot_encoded"
  kmer_frequencies: "data/processed/kmer_frequencies"
  embeddings: "data/processed/embeddings"

kmer_k: 3
num_workers: 4

embedding_file: "models/pretrained/dna2vec.txt"
